typography_spectrum: 0.5304731321521103
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.506306427763775
  lightness: 0.7688393695279956
  saturation: 0.13239890849217772
  rhythmicContrast: 0.11765604536049068
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36247302731499076
analytics:
  google: null
  facebook: null
  twitter: null
name: COG Cinemas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: COG Cinemas
description: Part of a Greater Machine
purpose: []
